<div class="bg-white rounded-2xl shadow-sm border border-slate-100 p-8 max-w-2xl">
    <form action="{{ $action }}" method="POST">
        @csrf
        @if($method !== 'POST') @method($method) @endif
        <div class="mb-5"><label class="block text-sm font-medium text-slate-700 mb-1.5">Appointment</label><select name="appointment_id" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-all duration-150">@foreach($appointments as $appointment)<option value="{{ $appointment->id }}" @selected(old('appointment_id', $prescription?->appointment_id) == $appointment->id)>{{ $appointment->patient_name }} - {{ $appointment->appointment_date->format('d M Y') }} - {{ $appointment->clinic->name ?? 'N/A' }}</option>@endforeach</select></div>
        <div class="mb-5"><label class="block text-sm font-medium text-slate-700 mb-1.5">Diagnosis</label><textarea name="diagnosis" rows="4" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-all duration-150">{{ old('diagnosis', $prescription?->diagnosis) }}</textarea></div>
        <div class="mb-5"><label class="block text-sm font-medium text-slate-700 mb-1.5">Medications</label><textarea name="medications" rows="5" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-all duration-150">{{ old('medications', $prescription?->medications) }}</textarea></div>
        <div class="mb-5"><label class="block text-sm font-medium text-slate-700 mb-1.5">Advice</label><textarea name="advice" rows="4" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-all duration-150">{{ old('advice', $prescription?->advice) }}</textarea></div>
        <div class="mb-5"><label class="block text-sm font-medium text-slate-700 mb-1.5">Follow Up Date</label><input type="date" name="follow_up_date" value="{{ old('follow_up_date', optional($prescription?->follow_up_date)->format('Y-m-d')) }}" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-all duration-150"></div>
        <button class="bg-orange-600 hover:bg-orange-700 text-white font-medium px-4 py-2 rounded-lg shadow-sm transition-all duration-150">Save Prescription</button>
    </form>
</div>
